# Generated by Django 5.2.7 on 2025-10-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="basic_auth_password",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="redirect",
            name="basic_auth_username",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
