# Generated by Django 5.2.7 on 2025-10-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redirects", "0002_redirect_basic_auth_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="redirect",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="enabled"),
        ),
    ]
